export interface Person {
  id: number;
  name: string;
  role: string;
  affiliation: string;
  initials: string;
  linkedin: string;
  photo: string;
}

export const PEOPLE: Person[] = [
  {
    id: 1,
    name: "Ir. Azkario Rizky Pratama, S.T., M.Eng., Ph.D., IPM",
    role: "Principal Investigator",
    affiliation: "Departemen Teknik Elektro dan Teknologi Informasi, UGM",
    initials: "ARP",
    linkedin: "https://www.linkedin.com/in/azkario-rizky-pratama-7ba8a934/",
    photo: "/photos/azkario.jpeg",
  },
  // UWB
  {
    id: 2,
    name: "Dhonan Nabil Hibatullah",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "DNH",
    linkedin: "https://www.linkedin.com/in/dhonan-nabil-hibatullah-1195a5200",
    photo: "/photos/dhonan.jpeg",
  },
  {
    id: 3,
    name: "Muhammad Rizqi",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "MR",
    linkedin: "https://www.linkedin.com/in/m-rizqi",
    photo: "/photos/MuhammadRizqi.jpeg",
  },
  {
    id: 4,
    name: "Rore",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "R",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  // Hyperbase
  {
    id: 5,
    name: "Muhammad Naufal Hilmy Makarim",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "MNH",
    linkedin: "https://www.linkedin.com/in/naufalhilmy/",
    photo: "/photos/NaufalHilmy.jpeg",
  },
  {
    id: 6,
    name: "Ahmad Fauzan",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "AF",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 7,
    name: "In'am Nurul Fuady",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "INF",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  // Borobudur
  {
    id: 8,
    name: "Rama",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Ra",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 9,
    name: "Fabian",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Fb",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 10,
    name: "Hanifah",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Hf",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 11,
    name: "Nadia",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Nd",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 12,
    name: "Brandon",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Br",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  // Smartlab
  {
    id: 13,
    name: "Petrus Aria Chevalier Rambing",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "PAC",
    linkedin: "https://linkedin.com/in/petrusariaa",
    photo: "/photos/petrusaria.jpeg",
  },
  {
    id: 14,
    name: "Muhammad Zufar Syaafi'",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "MZS",
    linkedin: "https://linkedin.com/in/muhammad-zufar-syaafi-410292321",
    photo: "/photos/zufar.jpeg",
  },
  {
    id: 15,
    name: "Pradana Yahya Abdillah",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "PYA",
    linkedin: "https://linkedin.com/in/pradana-yahya",
    photo: "/photos/pradana.jpeg",
  },
  {
    id: 16,
    name: "Rafif Raihan Bahrul Alam",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "RRB",
    linkedin: "https://linkedin.com/in/rafifraihan",
    photo: "/photos/foto-placeholder.jpg",
  },
  // Miniweather
  {
    id: 17,
    name: "Dr. Nur Abdillah Siddiq",
    role: "Researcher",
    affiliation: "DTETI, UGM",
    initials: "NAS",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 18,
    name: "Valen",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Vl",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 19,
    name: "Natanael Albert",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "NA",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  // CSI
  {
    id: 20,
    name: "Eduardus Bagus Wicaksono",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "EBW",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  // People Mobility
  {
    id: 21,
    name: "Dr. Widyawan",
    role: "Co-Investigator",
    affiliation: "DTETI, UGM",
    initials: "Wd",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 22,
    name: "Alfath Nuurlathif Sulistianto",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "ANS",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 23,
    name: "Siti Hashifah Qatrunnada",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "SHQ",
    linkedin: "https://www.linkedin.com/in/hashifaq",
    photo: "/photos/SitiHafishah.jpeg",
  },
  {
    id: 24,
    name: "Rizky Intan Nurlita",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "RIN",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 25,
    name: "Sagara Aldavy",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "SA",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 26,
    name: "Nurul Khairiza Utami",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "NKU",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 27,
    name: "Muhammad Noor Syams",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "MNS",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 28,
    name: "Handoko Wisnu Murti",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "HWM",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 29,
    name: "Muhamad Farrel Adrian",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "MFA",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 30,
    name: "Ayoub",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Ay",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  // Disaster
  {
    id: 31,
    name: "Muhammad Firas Zahid Suryaatmaja",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "MFZ",
    linkedin: "https://www.linkedin.com/in/muhammadfiras",
    photo: "/photos/firaszahid.jpeg",
  },
  {
    id: 32,
    name: "Michael Stephen Moses Pakpahan",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "MSM",
    linkedin: "https://www.linkedin.com/in/michael-pakpahan-951784230",
    photo: "/photos/michael.jpeg",
  },
  {
    id: 33,
    name: "Bagus Rakadyanto Oktavianto Putra",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "BRO",
    linkedin: "https://id.linkedin.com/in/bagus-raka",
    photo: "/photos/bagusraka.jpeg",
  },
  {
    id: 34,
    name: "Syahriani",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Sy",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
  {
    id: 35,
    name: "Dimas",
    role: "Student",
    affiliation: "DTETI, UGM",
    initials: "Di",
    linkedin: "",
    photo: "/photos/foto-placeholder.jpg",
  },
];
